import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({ meta: [{ title: "Disclaimer — souqss" }, { name: "description", content: "souqss disclaimer and limitation of liability." }] }),
  component: DisclaimerPage,
});

function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-10 border-b bg-card/95 backdrop-blur">
        <div className="container mx-auto flex max-w-3xl items-center gap-3 px-4 py-3">
          <Link to="/" className="grid h-9 w-9 place-items-center rounded-full hover:bg-muted" aria-label="Back home">
            <ArrowLeft className="h-5 w-5" />
          </Link>
          <h1 className="text-lg font-semibold">Disclaimer</h1>
        </div>
      </header>
      <main className="container mx-auto max-w-3xl px-4 py-8 prose prose-sm prose-neutral max-w-none">
        <h1>DISCLAIMER</h1>
        <p><em>Updated June 6, 2026</em></p>
        <p>souqss hereby grants you access to <strong>souqss.tech</strong> (the “Website”) and invites you to use the services offered here.</p>

        <h2>Definitions and key terms</h2>
        <ul>
          <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser.</li>
          <li><strong>Company:</strong> “Company,” “we,” “us,” or “our” refers to souqss.</li>
          <li><strong>Service:</strong> the service provided by souqss as described on this platform.</li>
          <li><strong>Website:</strong> souqss's site, accessible at souqss.tech.</li>
          <li><strong>You:</strong> a person or entity registered with souqss to use the Services.</li>
        </ul>

        <h2>Limited liability</h2>
        <p>souqss endeavours to update and supplement the content of the website regularly. Despite our care, content may be incomplete or incorrect. The materials offered are without any guarantee and may be changed at any time without prior notice. All prices are stated subject to typing and programming errors. souqss bears no liability for hyperlinks to third-party websites or services. When you leave our website, other sites may have different privacy policies and terms beyond our control.</p>

        <h2>Errors and Omissions</h2>
        <p>souqss is not responsible for any content, code, or other imprecision and does not provide warranties or guarantees. In no event shall souqss be liable for any special, direct, indirect, consequential, or incidental damages arising out of or in connection with the use of the Service.</p>

        <h2>General Disclaimer</h2>
        <p>The souqss Service and its contents are provided “as is” and “as available” without warranty or representation of any kind. souqss is a distributor and not a publisher of content supplied by third parties and exercises no editorial control over such content.</p>

        <h2>Copyright</h2>
        <p>All intellectual property rights concerning these materials are vested in souqss. Copying, distribution and other use is not permitted without written permission, except as provided by mandatory law.</p>

        <h2>Advertising</h2>
        <p>This website may contain third-party advertisements and links. souqss does not endorse third-party sites or take responsibility for the content of ads or the quality of products/services advertised.</p>

        <h2>Testimonials</h2>
        <p>Testimonials are opinions of those providing them and may not be indicative of results for other individuals.</p>

        <h2>Your Consent</h2>
        <p>By using our website, registering an account, or making a purchase, you consent to this Disclaimer.</p>

        <h2>Changes</h2>
        <p>We may update this Disclaimer. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>

        <h2>Contact Us</h2>
        <p>Email: <a href="mailto:hellosouqss@gmail.com">hellosouqss@gmail.com</a></p>
      </main>
    </div>
  );
}